import type {
  ChatSession,
  ImportTask,
  InsightDataset,
  LibraryItem,
  NotificationItem,
  PersonaModule,
  PersonaTimelineEvent,
  SettingsState,
  SummaryItem,
} from "@/types/desk";

export const navItems = [
  { key: "dashboard", label: "首页 Dashboard", href: "/" },
  { key: "library", label: "资料库", href: "/library" },
  { key: "summary", label: "摘要中心", href: "/summary" },
  { key: "persona", label: "人物画像", href: "/persona" },
  { key: "chat", label: "AI 对话", href: "/chat" },
  { key: "import", label: "导入中心", href: "/import" },
  { key: "insights", label: "成长回顾", href: "/insights" },
  { key: "settings", label: "设置", href: "/settings" },
] as const;

export const notifications: NotificationItem[] = [
  {
    id: "n1",
    title: "画像更新完成",
    body: "系统根据最近 12 条记录更新了你的“决策风格”和“高压状态表现”。",
    createdAt: "2026-04-23 09:20",
    read: false,
  },
  {
    id: "n2",
    title: "导入任务已完成",
    body: "《四月对话归档.md》已经完成清洗、摘要和入库。",
    createdAt: "2026-04-23 08:50",
    read: false,
  },
  {
    id: "n3",
    title: "周摘要已生成",
    body: "新的周摘要已经在摘要中心生成，可以查看证据链。",
    createdAt: "2026-04-22 22:10",
    read: true,
  },
];

export const libraryItems: LibraryItem[] = [
  {
    id: "lib-1",
    title: "今天早上的产品思考",
    type: "text",
    source: "mobile",
    createdAt: "2026-04-23T09:15:00+08:00",
    rawText:
      "我越来越确定，Second Me 的第一阶段必须把记录、摘要和画像之间的关系做清楚，不然产品会散。",
    summary: "确认了 MVP 的核心闭环应该是记录、摘要与画像。",
    tags: ["产品方向", "MVP", "优先级"],
    emotion: "平静、专注",
    inPersona: true,
    important: true,
    relatedMemoryIds: ["lib-5", "lib-7"],
  },
  {
    id: "lib-2",
    title: "晚间语音记录",
    type: "audio",
    source: "mobile",
    createdAt: "2026-04-23T20:35:00+08:00",
    rawText: "今天的推进感还不错，但决策时还是会担心做重了。",
    summary: "推进积极，但对实现重量仍有顾虑。",
    tags: ["情绪", "推进感"],
    emotion: "轻度焦虑",
    inPersona: true,
    important: false,
    relatedMemoryIds: ["lib-1"],
  },
  {
    id: "lib-3",
    title: "网页端结构草案",
    type: "text",
    source: "web",
    createdAt: "2026-04-22T14:10:00+08:00",
    rawText: "电脑端应该是中枢，不是后台。重点是资料、摘要、画像、聊天、导入、回顾。",
    summary: "明确电脑端是个人中枢，不是企业后台。",
    tags: ["网页中枢", "架构"],
    emotion: "清晰",
    inPersona: true,
    important: true,
    relatedMemoryIds: ["lib-1", "lib-8"],
  },
  {
    id: "lib-4",
    title: "与数字分身的一次聊天",
    type: "chat",
    source: "web",
    createdAt: "2026-04-21T21:05:00+08:00",
    rawText: "我现在最大的难点是既想做完整，又怕一开始做太重。",
    summary: "长期存在‘想做全’与‘怕做重’之间的拉扯。",
    tags: ["决策模式", "自我要求"],
    emotion: "纠结",
    inPersona: true,
    important: true,
    relatedMemoryIds: ["lib-2", "lib-6"],
  },
  {
    id: "lib-5",
    title: "四月聊天截图整理",
    type: "image",
    source: "import",
    createdAt: "2026-04-20T16:00:00+08:00",
    rawText: "聊天截图导入后提取出几段关于工作节奏的高频表达。",
    summary: "高频表达集中在工作节奏和计划拆解。",
    tags: ["导入", "截图", "工作节奏"],
    emotion: "客观",
    inPersona: false,
    important: false,
    relatedMemoryIds: ["lib-4"],
  },
  {
    id: "lib-6",
    title: "需求整理视频笔记",
    type: "video",
    source: "import",
    createdAt: "2026-04-18T11:40:00+08:00",
    rawText: "视频内容中提到了一个重要倾向：喜欢先搭结构，再追求细节完成度。",
    summary: "做事习惯偏向先结构后细节。",
    tags: ["工作习惯", "结构优先"],
    emotion: "稳定",
    inPersona: true,
    important: true,
    relatedMemoryIds: ["lib-4", "lib-8"],
  },
  {
    id: "lib-7",
    title: "本周复盘",
    type: "text",
    source: "web",
    createdAt: "2026-04-17T19:00:00+08:00",
    rawText: "这周比较明显的是，越是先把框架搭起来，后面越能稳住节奏。",
    summary: "框架先行有助于稳定执行节奏。",
    tags: ["周复盘", "节奏"],
    emotion: "积极",
    inPersona: true,
    important: true,
    relatedMemoryIds: ["lib-1", "lib-3"],
  },
  {
    id: "lib-8",
    title: "产品目标聊天纪要",
    type: "chat",
    source: "import",
    createdAt: "2026-04-12T10:25:00+08:00",
    rawText: "希望 Second Me 真正帮助自己慢慢看清，而不是堆更多信息。",
    summary: "长期目标偏向‘帮助自己看清’，而非信息堆叠。",
    tags: ["长期目标", "产品愿景"],
    emotion: "坚定",
    inPersona: true,
    important: true,
    relatedMemoryIds: ["lib-3", "lib-6"],
  },
];

export const summaries: SummaryItem[] = [
  {
    id: "sum-day-1",
    type: "day",
    title: "4 月 23 日日摘要",
    abstract: "今天的核心推进围绕‘把桌面端中枢做成可用产品而不是静态后台’展开。",
    generatedAt: "2026-04-23 21:30",
    modelVersion: "gpt-5.0-dashboard",
    evidenceRecordIds: ["lib-1", "lib-2"],
    relatedChatIds: ["chat-1"],
    relatedPersonaIds: ["persona-goals"],
  },
  {
    id: "sum-week-1",
    type: "week",
    title: "本周摘要",
    abstract: "本周连续在确认产品边界，长期目标更清晰，但仍会担心首版做重。",
    generatedAt: "2026-04-22 22:08",
    modelVersion: "gpt-5.0-weekly",
    evidenceRecordIds: ["lib-3", "lib-4", "lib-7"],
    relatedChatIds: ["chat-1"],
    relatedPersonaIds: ["persona-pressure"],
  },
  {
    id: "sum-month-1",
    type: "month",
    title: "四月月摘要",
    abstract: "四月的主题从‘记录工具’逐步转向‘理解自己的数字分身系统’。",
    generatedAt: "2026-04-20 20:10",
    modelVersion: "gpt-5.0-monthly",
    evidenceRecordIds: ["lib-5", "lib-8"],
    relatedChatIds: ["chat-2"],
    relatedPersonaIds: ["persona-goals", "persona-expression"],
  },
  {
    id: "sum-event-1",
    type: "event",
    title: "电脑中枢方向确定",
    abstract: "将桌面端重新定义为中枢节点之后，页面结构和功能优先级变得稳定。",
    generatedAt: "2026-04-22 14:30",
    modelVersion: "gpt-5.0-event",
    evidenceRecordIds: ["lib-3"],
    relatedChatIds: ["chat-2"],
    relatedPersonaIds: ["persona-goals"],
  },
  {
    id: "sum-topic-1",
    type: "topic",
    title: "主题摘要：节奏与做重焦虑",
    abstract: "近期多次出现‘怕做重’‘先搭结构’‘保持节奏’的组合表达。",
    generatedAt: "2026-04-21 19:20",
    modelVersion: "gpt-5.0-topic",
    evidenceRecordIds: ["lib-2", "lib-4", "lib-7"],
    relatedChatIds: ["chat-1", "chat-2"],
    relatedPersonaIds: ["persona-pressure", "persona-decision"],
  },
];

export const personaModules: PersonaModule[] = [
  {
    id: "persona-traits",
    title: "性格倾向",
    summary: "温和克制、结构导向，做决定前会尽量把系统边界想清楚。",
    confidence: 88,
    sourceRecordIds: ["lib-1", "lib-6"],
    sourceSummaryIds: ["sum-topic-1"],
    updatedAt: "2026-04-23",
  },
  {
    id: "persona-goals",
    title: "长期目标",
    summary: "希望构建一个能持续记录、理解并陪伴成长的个人数字分身系统。",
    confidence: 94,
    sourceRecordIds: ["lib-3", "lib-8"],
    sourceSummaryIds: ["sum-month-1"],
    updatedAt: "2026-04-23",
  },
  {
    id: "persona-topics",
    title: "近期关注主题",
    summary: "MVP 边界、桌面端中枢、资料与画像的关系、避免做重。",
    confidence: 90,
    sourceRecordIds: ["lib-1", "lib-3", "lib-7"],
    sourceSummaryIds: ["sum-week-1"],
    updatedAt: "2026-04-22",
  },
  {
    id: "persona-expression",
    title: "表达风格",
    summary: "习惯先给目标和原则，再逐步补充细节和约束。",
    confidence: 84,
    sourceRecordIds: ["lib-3", "lib-8"],
    sourceSummaryIds: ["sum-month-1"],
    updatedAt: "2026-04-22",
  },
  {
    id: "persona-decision",
    title: "决策风格",
    summary: "先搭结构、再收敛范围，偏好稳妥可扩展的方案。",
    confidence: 92,
    sourceRecordIds: ["lib-4", "lib-6", "lib-7"],
    sourceSummaryIds: ["sum-event-1"],
    updatedAt: "2026-04-23",
  },
  {
    id: "persona-pressure",
    title: "高压状态表现",
    summary: "在压力较大时容易反复担心做重，倾向于推迟开始。",
    confidence: 86,
    sourceRecordIds: ["lib-2", "lib-4"],
    sourceSummaryIds: ["sum-topic-1"],
    updatedAt: "2026-04-21",
  },
  {
    id: "persona-trigger",
    title: "情绪触发点",
    summary: "任务边界不清、交付期望过高、担心方向走偏时更容易焦虑。",
    confidence: 81,
    sourceRecordIds: ["lib-2", "lib-4"],
    sourceSummaryIds: ["sum-week-1"],
    updatedAt: "2026-04-21",
  },
  {
    id: "persona-relationship",
    title: "关系模式",
    summary: "在合作里重视清晰、尊重和共同推进，不喜欢不必要的空话。",
    confidence: 74,
    sourceRecordIds: ["lib-1", "lib-3"],
    sourceSummaryIds: ["sum-day-1"],
    updatedAt: "2026-04-20",
  },
];

export const personaTimeline: PersonaTimelineEvent[] = [
  {
    id: "pt-1",
    title: "决策风格从“谨慎”更新为“结构先行”",
    detail: "最近 3 次记录都体现出先搭结构、再收敛范围的工作方式。",
    createdAt: "2026-04-23 09:40",
    moduleId: "persona-decision",
  },
  {
    id: "pt-2",
    title: "长期目标置信度提升",
    detail: "关于 Second Me 的产品愿景表述趋于稳定，目标描述更清晰。",
    createdAt: "2026-04-22 20:15",
    moduleId: "persona-goals",
  },
  {
    id: "pt-3",
    title: "高压状态表现新增“担心做重”",
    detail: "本周聊天和语音记录都指向对复杂度的高敏感度。",
    createdAt: "2026-04-21 21:10",
    moduleId: "persona-pressure",
  },
];

export const chatSessions: ChatSession[] = [
  {
    id: "chat-1",
    title: "今天的状态梳理",
    group: "today",
    updatedAt: "10:24",
    messages: [
      {
        id: "m-1",
        role: "assistant",
        content: "我在。你可以把今天最想梳理的一件事告诉我。",
        createdAt: "10:10",
      },
      {
        id: "m-2",
        role: "user",
        content: "我觉得今天推进很多，但又怕后面做重。",
        createdAt: "10:22",
      },
      {
        id: "m-3",
        role: "assistant",
        content: "这说明你已经进入到“方向变清晰，但实现重量仍让你警惕”的阶段。我们可以先把要做的部分再拆一层。",
        createdAt: "10:24",
      },
    ],
    contextReferences: {
      "recent-memory": [
        {
          id: "ctx-r-1",
          type: "record",
          title: "今天早上的产品思考",
          detail: "最近记录里反复出现“避免做重”和“先搭结构”。",
        },
        {
          id: "ctx-r-2",
          type: "summary",
          title: "4 月 23 日日摘要",
          detail: "今天的推进集中在中枢定义和页面功能化。",
        },
      ],
      persona: [
        {
          id: "ctx-p-1",
          type: "persona",
          title: "决策风格",
          detail: "你偏好稳妥、可扩展的结构化方案。",
        },
        {
          id: "ctx-p-2",
          type: "persona",
          title: "高压状态表现",
          detail: "高压时会担心复杂度和方向偏差。",
        },
      ],
      "deep-retrieval": [
        {
          id: "ctx-d-1",
          type: "record",
          title: "网页端结构草案",
          detail: "电脑端应该是中枢，不是后台。",
        },
        {
          id: "ctx-d-2",
          type: "summary",
          title: "主题摘要：节奏与做重焦虑",
          detail: "近期高频主题集中在节奏与复杂度控制。",
        },
        {
          id: "ctx-d-3",
          type: "persona",
          title: "长期目标",
          detail: "目标是持续记录、理解并陪伴成长。",
        },
      ],
    },
  },
  {
    id: "chat-2",
    title: "产品方向确认",
    group: "recent",
    updatedAt: "昨天",
    messages: [
      {
        id: "m-4",
        role: "user",
        content: "桌面端到底是后台还是中枢？",
        createdAt: "昨天 20:12",
      },
      {
        id: "m-5",
        role: "assistant",
        content: "更准确的定义是“个人数字分身的电脑端中枢”，不是企业后台。",
        createdAt: "昨天 20:13",
      },
    ],
    contextReferences: {
      "recent-memory": [
        {
          id: "ctx-r-3",
          type: "record",
          title: "网页端结构草案",
          detail: "电脑端中枢的角色已经在记录中明确过。",
        },
      ],
      persona: [
        {
          id: "ctx-p-3",
          type: "persona",
          title: "长期目标",
          detail: "你追求的是理解自己的系统，而不是信息后台。",
        },
      ],
      "deep-retrieval": [
        {
          id: "ctx-d-4",
          type: "summary",
          title: "电脑中枢方向确定",
          detail: "方向确定之后页面结构明显稳定。",
        },
      ],
    },
  },
];

export const importTasks: ImportTask[] = [
  {
    id: "imp-1",
    fileName: "四月对话归档.md",
    fileType: "Markdown",
    createdAt: "2026-04-23 08:32",
    status: "done",
    progress: 100,
    inPersona: true,
    detail: "提取出 24 条对话片段，生成 3 条摘要，更新了 2 个画像模块。",
    steps: [
      { key: "clean", label: "清洗", detail: "去除重复段落与无关噪声", status: "done" },
      { key: "segment", label: "分段", detail: "按主题切成可处理片段", status: "done" },
      { key: "summary", label: "摘要", detail: "生成导入摘要", status: "done" },
      { key: "tag", label: "标签", detail: "自动打主题标签", status: "done" },
      { key: "index", label: "入库", detail: "写入资料库", status: "done" },
      { key: "persona", label: "画像更新", detail: "回写画像模块", status: "done" },
    ],
  },
  {
    id: "imp-2",
    fileName: "语音会议记录.m4a",
    fileType: "Audio",
    createdAt: "2026-04-23 10:10",
    status: "processing",
    progress: 62,
    inPersona: false,
    detail: "当前正在做转写摘要和标签生成。",
    steps: [
      { key: "clean", label: "清洗", detail: "音频预处理", status: "done" },
      { key: "segment", label: "分段", detail: "按时间段切片", status: "done" },
      { key: "summary", label: "摘要", detail: "生成阶段摘要", status: "processing" },
      { key: "tag", label: "标签", detail: "自动标签", status: "queued" },
      { key: "index", label: "入库", detail: "写入资料库", status: "queued" },
      { key: "persona", label: "画像更新", detail: "更新画像", status: "queued" },
    ],
  },
  {
    id: "imp-3",
    fileName: "旧笔记整理.zip",
    fileType: "Archive",
    createdAt: "2026-04-22 16:22",
    status: "failed",
    progress: 24,
    inPersona: false,
    detail: "压缩包内有一部分文件编码异常，等待重新处理。",
    steps: [
      { key: "clean", label: "清洗", detail: "识别文件结构", status: "done" },
      { key: "segment", label: "分段", detail: "提取文本片段", status: "failed" },
      { key: "summary", label: "摘要", detail: "生成摘要", status: "queued" },
      { key: "tag", label: "标签", detail: "自动标签", status: "queued" },
      { key: "index", label: "入库", detail: "写入资料库", status: "queued" },
      { key: "persona", label: "画像更新", detail: "更新画像", status: "queued" },
    ],
  },
];

export const insightsByRange: InsightDataset[] = [
  {
    range: "7d",
    recordTrend: [
      { label: "04/17", recordCount: 2, moodScore: 60 },
      { label: "04/18", recordCount: 3, moodScore: 68 },
      { label: "04/19", recordCount: 1, moodScore: 64 },
      { label: "04/20", recordCount: 4, moodScore: 72 },
      { label: "04/21", recordCount: 5, moodScore: 58 },
      { label: "04/22", recordCount: 4, moodScore: 74 },
      { label: "04/23", recordCount: 6, moodScore: 78 },
    ],
    themes: [
      { theme: "产品边界", value: 34 },
      { theme: "结构先行", value: 28 },
      { theme: "情绪整理", value: 18 },
      { theme: "计划执行", value: 20 },
    ],
    cards: [
      {
        id: "insight-1",
        title: "高价值记忆增长",
        summary: "本周被标记为重要的资料较上周增加 32%。",
        detail: "说明你更清楚哪些内容值得沉淀进长期理解系统。",
      },
      {
        id: "insight-2",
        title: "建议接受度",
        summary: "最近 AI 给出的拆解建议有更高的执行率。",
        detail: "你更愿意采用‘先搭结构、后补细节’的建议。",
      },
      {
        id: "insight-3",
        title: "行为偏好",
        summary: "在电脑端进行结构整理、在手机端进行即时记录的模式已形成。",
        detail: "这说明桌面中枢 + 手机采集的双端分工是有效的。",
      },
    ],
    milestones: [
      {
        id: "mile-1",
        title: "重新定义桌面端为中枢",
        detail: "页面结构从“后台感”转向“个人系统中枢”。",
        createdAt: "04/22",
      },
      {
        id: "mile-2",
        title: "本周记录连续 7 天",
        detail: "记录频率稳定，提高了摘要和画像质量。",
        createdAt: "04/23",
      },
    ],
  },
  {
    range: "30d",
    recordTrend: Array.from({ length: 10 }).map((_, index) => ({
      label: `W${index + 1}`,
      recordCount: 12 + (index % 4) * 3,
      moodScore: 55 + index * 3,
    })),
    themes: [
      { theme: "数字分身", value: 38 },
      { theme: "计划拆解", value: 22 },
      { theme: "工作节奏", value: 24 },
      { theme: "情绪观察", value: 16 },
    ],
    cards: [
      {
        id: "insight-4",
        title: "记录频率增长",
        summary: "近 30 天平均记录频率增长了 24%。",
        detail: "说明记录行为已经从偶发变成稳定习惯。",
      },
      {
        id: "insight-5",
        title: "主题收敛",
        summary: "高频主题逐渐收敛到产品边界、结构和理解自己。",
        detail: "主题更集中意味着目标更清晰。",
      },
      {
        id: "insight-6",
        title: "画像稳定度提升",
        summary: "人物画像模块的更新幅度开始下降。",
        detail: "说明画像正在从探索期进入稳定期。",
      },
    ],
    milestones: [
      {
        id: "mile-3",
        title: "确立长期目标表述",
        detail: "长期目标从模糊想法变为清晰的一句话。",
        createdAt: "04/09",
      },
      {
        id: "mile-4",
        title: "首次形成主题摘要",
        detail: "开始能稳定看到高频主题的重复出现。",
        createdAt: "04/16",
      },
    ],
  },
  {
    range: "90d",
    recordTrend: Array.from({ length: 12 }).map((_, index) => ({
      label: `M${index + 1}`,
      recordCount: 8 + (index % 5) * 2,
      moodScore: 52 + index * 2,
    })),
    themes: [
      { theme: "记录习惯", value: 24 },
      { theme: "自我理解", value: 28 },
      { theme: "产品方向", value: 31 },
      { theme: "执行节奏", value: 17 },
    ],
    cards: [
      {
        id: "insight-7",
        title: "长期结构偏好",
        summary: "近 90 天里，你越来越倾向于先搭结构再推进实现。",
        detail: "这是一个稳定的工作风格，不是偶发状态。",
      },
      {
        id: "insight-8",
        title: "高压触发更清晰",
        summary: "复杂度不确定与方向不清是最主要的压力来源。",
        detail: "这两个触发点在多个月的记录中反复出现。",
      },
      {
        id: "insight-9",
        title: "理解型产品倾向稳定",
        summary: "产品诉求长期稳定在“理解与陪伴”而不是“效率后台”。",
        detail: "这对后续产品形态选择有很强指导意义。",
      },
    ],
    milestones: [
      {
        id: "mile-5",
        title: "开始形成连续记录",
        detail: "记录行为不再零散。",
        createdAt: "02/12",
      },
      {
        id: "mile-6",
        title: "第一次出现‘数字分身’定义",
        detail: "产品目标开始具备连续性。",
        createdAt: "03/04",
      },
    ],
  },
];

export const settingsState: SettingsState = {
  userName: "Cendy",
  email: "cendy@secondme.local",
  autoSync: true,
  lastSyncAt: "2026-04-23 10:46",
  lightModel: "gpt-4.1-mini",
  deepModel: "gpt-5",
  autoUpdatePersona: true,
  dailyReminder: true,
  weeklyReviewReminder: true,
  analysisReadyReminder: false,
};
